"""Create all sync tables in BISHENG_FOR_AISHU with IDENTITY columns"""
import dmPython

conn = dmPython.connect(
    user='SYSDBA', password='6o+%s3z2NK7J',
    server='192.168.107.9', port=5236)
cur = conn.cursor()

SCHEMA = 'BISHENG_FOR_AISHU'

# Drop old tables
print(f"Dropping old tables in {SCHEMA}...")
tables = [
    'ANYSHARE_SYNC_AUDIT_EVENT', 'ANYSHARE_SYNC_DOCUMENT_MAPPING',
    'ANYSHARE_SYNC_FOLDER_MAPPING', 'ANYSHARE_SYNC_PERMISSION_SNAPSHOT',
    'ANYSHARE_SYNC_PRINCIPAL_MAPPING', 'ANYSHARE_SYNC_SCAN_RUN',
    'ANYSHARE_SYNC_SCOPE_CONFIG', 'ANYSHARE_SYNC_SPACE_MAPPING',
    'ANYSHARE_SYNC_TASK',
]
for t in tables:
    try:
        cur.execute(f'DROP TABLE "{SCHEMA}"."{t}" CASCADE')
        print(f"  Dropped {t}")
    except Exception as e:
        print(f"  {t}: not found (ok)")

# Create tables with IDENTITY on ID columns
print(f"\nCreating tables in {SCHEMA}...")

# DDL with IDENTITY columns — must escape { as {{ for f-string
ddl = f"""
CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_SCOPE_CONFIG" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    SOURCE_TYPE VARCHAR(32) NOT NULL,
    SOURCE_ID VARCHAR(1024) NOT NULL,
    SOURCE_NAME VARCHAR(256) NOT NULL,
    ENABLED BIT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX IDX_SCOPE_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_SCOPE_CONFIG"(TENANT_ID);

CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_SPACE_MAPPING" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    SOURCE_DOC_LIB_ID VARCHAR(1024) NOT NULL,
    SOURCE_DOC_LIB_NAME VARCHAR(256) NOT NULL,
    SOURCE_TYPE VARCHAR(32) NOT NULL,
    SOURCE_OWNER_ID VARCHAR(1024),
    TARGET_SPACE_ID INT,
    STATUS VARCHAR(32) DEFAULT 'pending' NOT NULL,
    AUTH_TYPE VARCHAR(16) DEFAULT 'public' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE(SOURCE_DOC_LIB_ID)
);
CREATE INDEX IDX_SPACE_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_SPACE_MAPPING"(TENANT_ID);
CREATE INDEX IDX_SPACE_TARGET ON "{SCHEMA}"."ANYSHARE_SYNC_SPACE_MAPPING"(TARGET_SPACE_ID);

CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_SCAN_RUN" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    SCAN_TYPE VARCHAR(32) NOT NULL,
    SCOPE_CONFIG_ID INT,
    STATUS VARCHAR(32) DEFAULT 'running' NOT NULL,
    TOTAL_FOLDERS INT DEFAULT 0 NOT NULL,
    TOTAL_FILES INT DEFAULT 0 NOT NULL,
    NEW_FILES INT DEFAULT 0 NOT NULL,
    UPDATED_FILES INT DEFAULT 0 NOT NULL,
    DELETED_FILES INT DEFAULT 0 NOT NULL,
    STARTED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    COMPLETED_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR(4096),
    PRIMARY KEY (ID)
);
CREATE INDEX IDX_SCAN_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_SCAN_RUN"(TENANT_ID);
CREATE INDEX IDX_SCAN_SCOPE ON "{SCHEMA}"."ANYSHARE_SYNC_SCAN_RUN"(SCOPE_CONFIG_ID);

CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_DOCUMENT_MAPPING" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    SPACE_MAPPING_ID INT NOT NULL,
    FOLDER_MAPPING_ID INT,
    SOURCE_DOC_ID VARCHAR(1024) NOT NULL,
    SOURCE_REV VARCHAR(256) DEFAULT '' NOT NULL,
    SOURCE_NAME VARCHAR(512) DEFAULT '' NOT NULL,
    SOURCE_SIZE INT DEFAULT 0 NOT NULL,
    CONTENT_VERSION VARCHAR(256) DEFAULT '' NOT NULL,
    METADATA_HASH VARCHAR(256) DEFAULT '' NOT NULL,
    POLICY_HASH VARCHAR(256) DEFAULT '' NOT NULL,
    TARGET_FILE_ID INT,
    TARGET_DOCUMENT_ID INT,
    TARGET_VERSION_ID INT,
    TARGET_UPLOAD_REF VARCHAR(4096),
    IDEMPOTENCY_KEY VARCHAR(256) DEFAULT '' NOT NULL,
    CURRENT_ACTION VARCHAR(32) DEFAULT '' NOT NULL,
    STATUS VARCHAR(32) DEFAULT 'discovered' NOT NULL,
    NEXT_CHECK_AT TIMESTAMP,
    LAST_SEEN_SCAN_ID INT,
    MISSING_COUNT INT DEFAULT 0 NOT NULL,
    RETRY_COUNT INT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE(SOURCE_DOC_ID)
);
CREATE INDEX IDX_DOC_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_DOCUMENT_MAPPING"(TENANT_ID);
CREATE INDEX IDX_DOC_SPACE ON "{SCHEMA}"."ANYSHARE_SYNC_DOCUMENT_MAPPING"(SPACE_MAPPING_ID);
CREATE INDEX IDX_DOC_FOLDER ON "{SCHEMA}"."ANYSHARE_SYNC_DOCUMENT_MAPPING"(FOLDER_MAPPING_ID);
CREATE INDEX IDX_DOC_TARGET ON "{SCHEMA}"."ANYSHARE_SYNC_DOCUMENT_MAPPING"(TARGET_FILE_ID);
CREATE INDEX IDX_DOC_IDEMKEY ON "{SCHEMA}"."ANYSHARE_SYNC_DOCUMENT_MAPPING"(IDEMPOTENCY_KEY);

CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_FOLDER_MAPPING" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    SPACE_MAPPING_ID INT NOT NULL,
    SOURCE_FOLDER_ID VARCHAR(1024) NOT NULL,
    SOURCE_PARENT_ID VARCHAR(1024),
    SOURCE_NAME VARCHAR(256) NOT NULL,
    SOURCE_REV VARCHAR(256) DEFAULT '' NOT NULL,
    SOURCE_PATH VARCHAR(4096) DEFAULT '' NOT NULL,
    TARGET_SPACE_ID INT,
    TARGET_FOLDER_ID INT,
    TARGET_PARENT_ID INT,
    METADATA_HASH VARCHAR(256) DEFAULT '' NOT NULL,
    POLICY_HASH VARCHAR(256) DEFAULT '' NOT NULL,
    LEVEL INT DEFAULT 0 NOT NULL,
    LAST_SEEN_SCAN_ID INT,
    MISSING_COUNT INT DEFAULT 0 NOT NULL,
    STATUS VARCHAR(32) DEFAULT 'active' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX IDX_FOLDER_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_FOLDER_MAPPING"(TENANT_ID);
CREATE INDEX IDX_FOLDER_SPACE ON "{SCHEMA}"."ANYSHARE_SYNC_FOLDER_MAPPING"(SPACE_MAPPING_ID);
CREATE INDEX IDX_FOLDER_TARGET ON "{SCHEMA}"."ANYSHARE_SYNC_FOLDER_MAPPING"(TARGET_FOLDER_ID);

CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_PRINCIPAL_MAPPING" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    SOURCE_ID VARCHAR(1024) NOT NULL,
    SOURCE_TYPE VARCHAR(32) NOT NULL,
    SOURCE_NAME VARCHAR(256) NOT NULL,
    TARGET_ID INT,
    STATUS VARCHAR(32) DEFAULT 'identity_pending' NOT NULL,
    MATCH_METHOD VARCHAR(32) DEFAULT '' NOT NULL,
    EXTRA VARCHAR(4096) DEFAULT '{}' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX IDX_PRIN_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_PRINCIPAL_MAPPING"(TENANT_ID);
CREATE INDEX IDX_PRIN_TARGET ON "{SCHEMA}"."ANYSHARE_SYNC_PRINCIPAL_MAPPING"(TARGET_ID);

CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_PERMISSION_SNAPSHOT" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    SPACE_MAPPING_ID INT,
    DOCUMENT_MAPPING_ID INT,
    RESOURCE_TYPE VARCHAR(32) NOT NULL,
    RESOURCE_ID VARCHAR(1024) NOT NULL,
    SOURCE_ACL_RAW CLOB DEFAULT '{{}}' NOT NULL,
    TARGET_FGA_TUPLES CLOB DEFAULT '[]' NOT NULL,
    POLICY_HASH VARCHAR(256) DEFAULT '' NOT NULL,
    IS_BLOCKED BIT DEFAULT 0 NOT NULL,
    BLOCK_REASON VARCHAR(1024) DEFAULT '' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX IDX_SNAP_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_PERMISSION_SNAPSHOT"(TENANT_ID);
CREATE INDEX IDX_SNAP_SPACE ON "{SCHEMA}"."ANYSHARE_SYNC_PERMISSION_SNAPSHOT"(SPACE_MAPPING_ID);
CREATE INDEX IDX_SNAP_DOC ON "{SCHEMA}"."ANYSHARE_SYNC_PERMISSION_SNAPSHOT"(DOCUMENT_MAPPING_ID);
CREATE INDEX IDX_SNAP_HASH ON "{SCHEMA}"."ANYSHARE_SYNC_PERMISSION_SNAPSHOT"(POLICY_HASH);

CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_AUDIT_EVENT" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    TRACE_ID VARCHAR(128) NOT NULL,
    ACTION VARCHAR(64) NOT NULL,
    SOURCE_TYPE VARCHAR(32),
    SOURCE_ID VARCHAR(1024),
    SOURCE_REV VARCHAR(256),
    TARGET_TYPE VARCHAR(32),
    TARGET_ID INT,
    OPERATOR VARCHAR(128) DEFAULT 'system' NOT NULL,
    RESULT VARCHAR(32) DEFAULT 'success' NOT NULL,
    DETAIL CLOB DEFAULT '{{}}' NOT NULL,
    POLICY_HASH VARCHAR(256),
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX IDX_AUDIT_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_AUDIT_EVENT"(TENANT_ID);
CREATE INDEX IDX_AUDIT_TRACE ON "{SCHEMA}"."ANYSHARE_SYNC_AUDIT_EVENT"(TRACE_ID);

CREATE TABLE "{SCHEMA}"."ANYSHARE_SYNC_TASK" (
    ID INT IDENTITY(1,1) NOT NULL,
    TENANT_ID INT DEFAULT 1 NOT NULL,
    SCAN_RUN_ID INT,
    IDEMPOTENCY_KEY VARCHAR(256) NOT NULL,
    ACTION VARCHAR(32) NOT NULL,
    SOURCE_DOC_ID VARCHAR(1024) NOT NULL,
    SOURCE_REV VARCHAR(256) DEFAULT '' NOT NULL,
    TARGET_SPACE_ID INT,
    TARGET_FILE_ID INT,
    STATUS VARCHAR(32) DEFAULT 'pending' NOT NULL,
    RETRY_COUNT INT DEFAULT 0 NOT NULL,
    MAX_RETRIES INT DEFAULT 6 NOT NULL,
    NEXT_RETRY_AT TIMESTAMP,
    LEASE_HOLDER VARCHAR(128) DEFAULT '' NOT NULL,
    LEASE_EXPIRES_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR(4096),
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE(IDEMPOTENCY_KEY)
);
CREATE INDEX IDX_TASK_TENANT ON "{SCHEMA}"."ANYSHARE_SYNC_TASK"(TENANT_ID);
CREATE INDEX IDX_TASK_SCAN ON "{SCHEMA}"."ANYSHARE_SYNC_TASK"(SCAN_RUN_ID);
CREATE INDEX IDX_TASK_SPACE ON "{SCHEMA}"."ANYSHARE_SYNC_TASK"(TARGET_SPACE_ID);
CREATE INDEX IDX_TASK_KEY ON "{SCHEMA}"."ANYSHARE_SYNC_TASK"(IDEMPOTENCY_KEY);
"""

# Execute each statement separately
for stmt in ddl.split(';'):
    stmt = stmt.strip()
    if stmt:
        try:
            cur.execute(stmt)
        except Exception as e:
            print(f"  Error: {e}")
            print(f"  SQL: {stmt[:100]}...")

# Verify
print(f"\nTables in {SCHEMA}:")
cur.execute(f"SELECT table_name FROM dba_tables WHERE owner='{SCHEMA}' ORDER BY table_name")
for r in cur.fetchall():
    cur.execute(f"SELECT COUNT(*) FROM \"{SCHEMA}\".\"{r[0]}\"")
    print(f"  {r[0]} ({cur.fetchone()[0]} rows)")

# Check ID column
print(f"\nID column check:")
cur.execute(f"SELECT COLUMN_NAME, DATA_TYPE, DATA_DEFAULT FROM dba_tab_columns WHERE owner='{SCHEMA}' AND table_name='ANYSHARE_SYNC_SCOPE_CONFIG' AND COLUMN_NAME='ID'")
for r in cur.fetchall():
    print(f"  {r}")

conn.close()
print("\n>>> Done <<<")
