"""Create all sync tables in BISHENG_FOR_AISHU — Dameng raw SQL"""
import dmPython

SCHEMA = 'BISHENG_FOR_AISHU'

conn = dmPython.connect(
    user='SYSDBA', password='6o+%s3z2NK7J',
    server='192.168.107.9', port=5236)
cur = conn.cursor()

# Drop all
for t in ['ANYSHARE_SYNC_AUDIT_EVENT','ANYSHARE_SYNC_DOCUMENT_MAPPING',
          'ANYSHARE_SYNC_FOLDER_MAPPING','ANYSHARE_SYNC_PERMISSION_SNAPSHOT',
          'ANYSHARE_SYNC_PRINCIPAL_MAPPING','ANYSHARE_SYNC_SCAN_RUN',
          'ANYSHARE_SYNC_SCOPE_CONFIG','ANYSHARE_SYNC_SPACE_MAPPING',
          'ANYSHARE_SYNC_TASK']:
    try:
        cur.execute('DROP TABLE "' + SCHEMA + '"."' + t + '" CASCADE')
    except: pass
print('Old tables dropped')

# Minimal DDL — no string defaults, only INT defaults + TIMESTAMP
tables = {
    "ANYSHARE_SYNC_SCOPE_CONFIG": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1, SOURCE_TYPE VARCHAR(32),
        SOURCE_ID VARCHAR(1024), SOURCE_NAME VARCHAR(256),
        ENABLED BIT DEFAULT 1, CREATED_AT TIMESTAMP DEFAULT SYSDATE,
        UPDATED_AT TIMESTAMP DEFAULT SYSDATE, PRIMARY KEY (ID))""",

    "ANYSHARE_SYNC_SPACE_MAPPING": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1,
        SOURCE_DOC_LIB_ID VARCHAR(1024), SOURCE_DOC_LIB_NAME VARCHAR(256),
        SOURCE_TYPE VARCHAR(32), SOURCE_OWNER_ID VARCHAR(1024),
        TARGET_SPACE_ID INT, "STATUS" VARCHAR(32),
        AUTH_TYPE VARCHAR(16), CREATED_AT TIMESTAMP DEFAULT SYSDATE,
        UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
        PRIMARY KEY (ID), UNIQUE(SOURCE_DOC_LIB_ID))""",

    "ANYSHARE_SYNC_SCAN_RUN": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1, SCAN_TYPE VARCHAR(32),
        SCOPE_CONFIG_ID INT, "STATUS" VARCHAR(32),
        TOTAL_FOLDERS INT DEFAULT 0, TOTAL_FILES INT DEFAULT 0,
        NEW_FILES INT DEFAULT 0, UPDATED_FILES INT DEFAULT 0,
        DELETED_FILES INT DEFAULT 0, STARTED_AT TIMESTAMP DEFAULT SYSDATE,
        COMPLETED_AT TIMESTAMP, ERROR_MESSAGE VARCHAR(4096), PRIMARY KEY (ID))""",

    "ANYSHARE_SYNC_DOCUMENT_MAPPING": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1, SPACE_MAPPING_ID INT,
        FOLDER_MAPPING_ID INT, SOURCE_DOC_ID VARCHAR(1024),
        SOURCE_REV VARCHAR(256), SOURCE_NAME VARCHAR(512),
        SOURCE_SIZE INT DEFAULT 0, CONTENT_VERSION VARCHAR(256),
        METADATA_HASH VARCHAR(256), POLICY_HASH VARCHAR(256),
        TARGET_FILE_ID INT, TARGET_DOCUMENT_ID INT, TARGET_VERSION_ID INT,
        TARGET_UPLOAD_REF VARCHAR(4096), IDEMPOTENCY_KEY VARCHAR(256),
        CURRENT_ACTION VARCHAR(32), "STATUS" VARCHAR(32),
        NEXT_CHECK_AT TIMESTAMP, LAST_SEEN_SCAN_ID INT,
        MISSING_COUNT INT DEFAULT 0, RETRY_COUNT INT DEFAULT 0,
        CREATED_AT TIMESTAMP DEFAULT SYSDATE,
        UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
        PRIMARY KEY (ID), UNIQUE(SOURCE_DOC_ID))""",

    "ANYSHARE_SYNC_FOLDER_MAPPING": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1, SPACE_MAPPING_ID INT,
        SOURCE_FOLDER_ID VARCHAR(1024), SOURCE_PARENT_ID VARCHAR(1024),
        SOURCE_NAME VARCHAR(256), SOURCE_REV VARCHAR(256),
        SOURCE_PATH VARCHAR(4096), TARGET_SPACE_ID INT, TARGET_FOLDER_ID INT,
        TARGET_PARENT_ID INT, METADATA_HASH VARCHAR(256),
        POLICY_HASH VARCHAR(256), "LEVEL" INT DEFAULT 0,
        LAST_SEEN_SCAN_ID INT, MISSING_COUNT INT DEFAULT 0,
        "STATUS" VARCHAR(32), CREATED_AT TIMESTAMP DEFAULT SYSDATE,
        UPDATED_AT TIMESTAMP DEFAULT SYSDATE, PRIMARY KEY (ID))""",

    "ANYSHARE_SYNC_PRINCIPAL_MAPPING": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1,
        SOURCE_ID VARCHAR(1024), SOURCE_TYPE VARCHAR(32),
        SOURCE_NAME VARCHAR(256), TARGET_ID INT, "STATUS" VARCHAR(32),
        MATCH_METHOD VARCHAR(32), EXTRA VARCHAR(4096),
        CREATED_AT TIMESTAMP DEFAULT SYSDATE,
        UPDATED_AT TIMESTAMP DEFAULT SYSDATE, PRIMARY KEY (ID))""",

    "ANYSHARE_SYNC_PERMISSION_SNAPSHOT": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1,
        SPACE_MAPPING_ID INT, DOCUMENT_MAPPING_ID INT,
        RESOURCE_TYPE VARCHAR(32), RESOURCE_ID VARCHAR(1024),
        SOURCE_ACL_RAW CLOB, TARGET_FGA_TUPLES CLOB,
        POLICY_HASH VARCHAR(256), IS_BLOCKED BIT DEFAULT 0,
        BLOCK_REASON VARCHAR(1024), CREATED_AT TIMESTAMP DEFAULT SYSDATE,
        PRIMARY KEY (ID))""",

    "ANYSHARE_SYNC_AUDIT_EVENT": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1, TRACE_ID VARCHAR(128),
        "ACTION" VARCHAR(64), SOURCE_TYPE VARCHAR(32), SOURCE_ID VARCHAR(1024),
        SOURCE_REV VARCHAR(256), TARGET_TYPE VARCHAR(32), TARGET_ID INT,
        OPERATOR VARCHAR(128), "RESULT" VARCHAR(32),
        DETAIL CLOB, POLICY_HASH VARCHAR(256),
        CREATED_AT TIMESTAMP DEFAULT SYSDATE, PRIMARY KEY (ID))""",

    "ANYSHARE_SYNC_TASK": """(
        ID INT IDENTITY(1,1), TENANT_ID INT DEFAULT 1, SCAN_RUN_ID INT,
        IDEMPOTENCY_KEY VARCHAR(256), "ACTION" VARCHAR(32),
        SOURCE_DOC_ID VARCHAR(1024), SOURCE_REV VARCHAR(256),
        TARGET_SPACE_ID INT, TARGET_FILE_ID INT, "STATUS" VARCHAR(32),
        RETRY_COUNT INT DEFAULT 0, MAX_RETRIES INT DEFAULT 6,
        NEXT_RETRY_AT TIMESTAMP, LEASE_HOLDER VARCHAR(128),
        LEASE_EXPIRES_AT TIMESTAMP, ERROR_MESSAGE VARCHAR(4096),
        CREATED_AT TIMESTAMP DEFAULT SYSDATE,
        UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
        PRIMARY KEY (ID), UNIQUE(IDEMPOTENCY_KEY))""",
}

for name, ddl in tables.items():
    sql = 'CREATE TABLE "' + SCHEMA + '"."' + name + '" ' + ddl
    try:
        cur.execute(sql)
        print('  OK: ' + name)
    except Exception as e:
        print('  ERR: ' + name + ' - ' + str(e)[:120])

# Verify
print('\nTables in ' + SCHEMA + ':')
cur.execute("SELECT table_name FROM dba_tables WHERE owner='" + SCHEMA + "' ORDER BY table_name")
for r in cur.fetchall():
    print('  ' + r[0])

conn.close()
print('\nDone')
